networks:
  devcontainer:
    internal: false
  nginx:
    internal: false
  oracle:
    internal: true
  php:
    internal: true
  valkey:
    internal: true
services:
  devcontainer:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'devcontainer'
    command: 'sleep infinity'
    depends_on:
      nginx:
        condition: 'service_healthy'
      oracle:
        condition: 'service_healthy'
      php:
        condition: 'service_healthy'
      valkey:
        condition: 'service_healthy'
    environment:
      APP_ENV: 'local'
      COMPOSER_CACHE_DIR: '/home/devcontainer/.composer/cache'
      NODE_ENV: 'development'
      NPM_CONFIG_CACHE: '/home/devcontainer/.npm'
      ORACLE_DATABASE: 'FREEPDB1'
      ORACLE_HOST: 'oracle'
      ORACLE_PASSWORD: '/run/secrets/oracle_pwd'
      ORACLE_UNIT_USER: 'APP_UNIT'
      ORACLE_USER: 'APP'
    init: true
    networks:
      - 'devcontainer'
      - 'nginx'
      - 'oracle'
      - 'php'
      - 'valkey'
    secrets:
      - 'oracle_pwd'
    user: 'devcontainer:devcontainer'
    volumes:
      - './:/var/www/html'
      - 'composer-cache:/home/devcontainer/.composer/cache'
      - 'npm-cache:/home/devcontainer/.npm'
  nginx:
    ports:
      - host_ip: '127.0.0.1'
        protocol: 'tcp'
        target: 8080
    volumes:
      - './:/var/www/html'
  php:
    build:
      context: './'
      dockerfile: './Dockerfile'
      target: 'devcontainer'
    environment:
      APP_ENV: 'local'
      NODE_ENV: 'development'
    volumes:
      - './:/var/www/html'
volumes:
  composer-cache:
    external: true
    name: 'tomaschochola-composer-cache'
  npm-cache:
    external: true
    name: 'tomaschochola-npm-cache'
